/**
 * Auth Module Types and Interfaces
 */

import { UserRole } from '../user/user.interfaces';

// ============================================================================
// ENUMS
// ============================================================================

export enum TokenType {
  ACCESS = 'access',
  REFRESH = 'refresh',
}

// ============================================================================
// BASE INTERFACES
// ============================================================================

/**
 * Base user credential properties for signup
 */
interface IUserCredentials {
  email: string;
  username: string;
  password: string;
}

/**
 * Base token payload properties
 */
interface IBaseTokenPayload {
  sub: string; // User ID
  type: TokenType;
  iat?: number; // Issued at
  exp?: number; // Expiration
}

// ============================================================================
// USER CREATION INTERFACES
// ============================================================================

/**
 * Signup/user creation request (from client)
 */
export interface ISignupRequest extends IUserCredentials {}

/**
 * New user entity (with generated key for database insertion)
 */
export interface INewUser extends IUserCredentials {
  key: string;
}

// ============================================================================
// OTP INTERFACES
// ============================================================================

/**
 * OTP record in database
 */
export interface IOtpRecord {
  id?: number; // Database ID (internal use only)
  user_key: string;
  otp_hash: string;
  expires_at: Date;
  created_at?: Date; // Auto-generated by database
}

/**
 * OTP verification request
 */
export interface IVerifyOtpRequest {
  userKey: string;
  otp: string;
}

// ============================================================================
// AUTHENTICATION REQUEST INTERFACES
// ============================================================================

/**
 * Login request (email or username + password)
 */
export interface ILoginRequest {
  email?: string;
  username?: string;
  password: string;
}

// ============================================================================
// TOKEN INTERFACES
// ============================================================================

/**
 * Authentication tokens pair
 */
export interface IAuthTokens {
  accessToken: string;
  refreshToken: string;
}

/**
 * Access token payload — kept minimal. `sub` is the user key.
 * `role` is included so authorization checks don't hit the DB.
 * Profile fields (email, username) live on the user record, not the token.
 */
export interface IAccessTokenPayload extends IBaseTokenPayload {
  role: UserRole;
}

/**
 * Refresh token payload (sub + type only)
 */
export interface IRefreshTokenPayload extends IBaseTokenPayload {}
